### ISSUE TITLE
Bidirectional Latency Measurement

### ISSUE THREAD

**Issue by stefan-ramdhan** [vladimiroltean/isochron#15]
Hello,

Great tool you have here. I'm curious if there is a plan to expand the scope of this project to measure bidirectional latency, or whether this is possible already. I have tried doing this by running both an isochron sender and receiver on my gPTP GM, and an isochron sender and receiver on my gPTP Slave, but, first, I'm not sure if this is an expected usecase of isochron, so I'm not sure if the results I'm seeing are correct. Secondly, I get some errors on the PTP slave from the isochron send process:

`Premature transmission detected for seqid 1 scheduled for 1687969573.400000000: TX hwts 1687969573.350410276
Timed out waiting for TX timestamps, 600 timestamps unacknowledged`

At the same time, on the PTP GM from the isochron send process, I'm getting:
`Timed out waiting for TX timestamps, 527 timestamps unacknowledged
seqid 74 missing timestamps: sw,
seqid 75 missing timestamps: hw, sw, sched,
seqid 75 missing timestamps: hw, sw, sched,
...
`

These errors only happen when I run isochron send and receive on the same machine, for both my PTP GM and Slave.
My main questions are: 
1. Even if I were to get timestamps for this isochron send process running on the PTP slave, would the results be something I can trust?
2. Why are timestamps going missing on the GM side? 
3. Slightly unrelated, but if I were to have a network consisting of more than just a GM and slave, let's say with a TSN bridge in the middle, do I have to run isochron on the TSN bridge? Or just on the Endstations.

**Comment by vladimiroltean** [comment]
1. A bidirectional stream is composed of 2 unidirectional streams, really. With isochron-orchestrate, you can start a receiver and a daemon on each node, and you can very precisely time the individual transmission of the 2 nodes in a synchronized fashion. That use case should work.
2. I don't know why timestamps are missing, probably the kernel driver for the NIC is to blame for that. Which hardware and driver is it? `realpath /sys/class/net/eth0/device/driver` should be able to say more.
3. You don't have to start isochron on the bridge, only on the endpoints.

**Comment by stefan-ramdhan** [comment]
Alright, I'll have a look at bidirectional streams later. However, the more pressing issue for me is that ptp4l goes into a fault state whenever I startup an isochron send process on my Master. To make things clear, I'll briefly explain my network.

2 PCs:
1 GM with `Intel I210-T1` NIC. Driver: `igb`. Output of `realpath /sys/class/net/eth0/device/driver` is `/sys/bus/pci/drivers/igb`. Logical name: `enp1s0`

1 Slave with `Intel I210-T1` NIC. Driver: `igb`. Output of `realpath /sys/class/net/eth0/device/driver` is `/sys/bus/pci/drivers/igb`. Logical name: `enp1s0`

ptp4l is working fine whenever isochron is not running. The command I'm using to run ptp4l on the GM is:
`sudo ptp4l -i enp1s0.5 -f configs/gPTP.cfg --step_threshold=1 -m`. Only thing different about my gPTP.cfg compared with out of the box gPTP.cfg is that I am using `socket_priority 7`. 
For phc2sys, the command I'm running is:
`sudo phc2sys -a -rr --transportSpecific=1 -m`

 I run an `isochron rcv` on the Slave using: 
`sudo isochron rcv -i enp1s0 -d 01:80:C2:00:00:0E`
and `isochron send` on the GM using:
`sudo isochron send -i enp1s0 --client 10.0.0.2 -c 0.1 -s 64 -t 1 -X 20000 -Q -w 100000000 -F 1-isochron.dat -n 600 -v 5 -p 6`

As you can see, I am using different socket priorities for ptp4l and for isochron. Using taprio however, I always have the gates associated with PCP 6 and 7 open. Just for reference, this is the taprio settings I'm using:
`sudo tc qdisc replace dev enp1s0 parent root handle 100 taprio num_tc 4 queues 1@0 1@1 1@2 1@3 map 0 0 0 0 0 1 2 3 0 0 0 0 0 0 0 0 \
       sched-entry S c 100000 \
        sched-entry S e 100000 \
        sched-entry S f 100000 \
        clockid CLOCK_TAI`

**### The problem:**
Whenever I start up `isochron send`, it'll take some measurements, but then, will always cause ptp4l to go into a fault state, as shown below.
![isochron_failure](https://github.com/vladimiroltean/isochron/assets/90281113/d831e76d-decc-4c52-be4a-2e0f34c3cca9)
![ptp4l_fault](https://github.com/vladimiroltean/isochron/assets/90281113/5618922f-d9d3-45e9-ba3b-5aa98dd127a9)

Weirdly enough, this doesn't happen when I start the `isochron rcv` on my Master, then `isochron send` on my Slave.
I thought this might have to do with `isochron` and `ptp4l` competing over the same CPU resources. So, I set the CPU affinity for ptp4l to only use CPU 0, and isochron to use CPU 1 using:
`sudo taskset -p 0x1 {pidof ptp4l}` and `sudo taskset -p 0x2 {pidof isochron}`. For isochron, you can use the `--cpu-mask` argument. I tried this as well, and the same fault happens. I also tried setting the scheduler for both isochron and ptp4l to SCHED_FIFO, with priority 99 for ptp4l, and 98 for isochron. Again, when I start isochron send, the same fault happens, and isochron can never finish running its measurements for the 60 seconds.

Any idea what might be the cause of this?

**Comment by stefan-ramdhan** [comment]
I'd also like to mention that I have been playing around with various parameters, such as the RT scheduling priority of both the ptp4l process as well as the isochron sender thread, and the main isochron process. Also the affinity of all the processes + cpu-mask of the isochron sender. I was tipped off by  [this email thread that you were on](https://lore.kernel.org/netdev/87tu7emqb9.fsf@intel.com/T/#md4b70ab6e190a01f5857e08cb9bd194966d309e3) where Feneric had solved his issues with missing TX HW timestamps by setting the affinity of the isochron sender thread (using --cpu-mask) to the same CPU that the igc_ptp_tx_work was on. I tried this (using the igb equivalent), but, still, no change in ptp4l faulting. 

I tried using `chrt` to set the sched for ptp4l to SCHED_FIFO, priority 99. Then using isochron flags to set the scheduler to SCHED_FIFO, priority 98 (using `--sched-fifo -H 98`). However, isochron still causes ptp4l to fault. Further, it takes a variable amount of time to cause a fault in ptp4l. Sometimes, it faults within the first 2 seconds, sometimes, it faults around 50 seconds, and very rarely does it complete a full 60 second run. 

I also tried using `taskset -p 1 $(pidof ptp4l)` and `--cpu-mask $((1 << 0))` option to run ptp4l and the isochron sender thread on the same core as each other. Then I tried running them on different cores, and still, ptp4l faults when isochron starts up. 

I do notice that whenever ptp4l faults when isochron is running, the amount of `tx_hwtstamp_skipped` (from `ethtool -S`) increases by around 2 or 3. 

I'm not sure what other things I can play with to try solving this issue. I doubt this is an issue with the igb driver, since it's been around for so long, and this is a pretty common usecase I'm using it for.

**Comment by vladimiroltean** [comment]
> I doubt this is an issue with the igb driver, since it's been around for so long, and this is a pretty common usecase I'm using it for.

I would like to contradict your logic; the use case to request hardware TX timestamping of non-PTP packets at a high data rate is not so common, and thus, the driver's age is not an argument in its favor.

I have no direct experience with the i210 hardware, but my understanding is that there can only be one packet requesting a hardware TX timestamp in flight at a time, due to the single TXSTMPL/TXSTMPH register. For i225/i226 the hardware limit was increased to 4, which is still "not great", and the igc driver also has a software limitation of a single in-flight packet currently. If only PTP event frames have to be timestamped, the hardware and driver can wing it, because the data rate isn't so high. However, even multiple PTP time domains seem to be challenging to these NICs from what I can gather.

My poor understanding is that the driver may offer, as an alternative to true MAC hardware timestamps, these so-called DMA timestamps. This should also be supported by the i210 hardware, but I don't believe they're exposed either by the igb or igc drivers. Also, I am a bit skeptical regarding the quality of DMA timestamps.

Here are some recent discussions from the mailing lists on the topic:
https://lore.kernel.org/netdev/20221018010733.4765-1-muhammad.husaini.zulkifli@intel.com/
https://lore.kernel.org/netdev/20230511203646.ihljeknxni77uu5j@skbuf/

My recommendation is to gather the email addresses and mailing lists listed by `./scripts/get_maintainer.pl drivers/net/ethernet/intel/igb` from a kernel tree, and send them a message asking for suggestions.

**Comment by stefan-ramdhan** [comment]
You're absolutely right, I was wrong to assume this wasn't an issue with the igb driver. Well... this is an issue with the hardware itself. I wonder if having only one set of registers to deal with HW TX timestamps is a normal practice with these TSN NICs. I'll take a look at the DMA timestamps, thanks. Btw, increasing the tx_timestamp_timeout parameter from 1 to 10 for ptp4l alleviated this issue.

Also, thanks for pointing me to the email threads. If you'd like, I can send a message to this issue if I do end up playing around with the DMA timestamps, and whether they worked for me, or not. Might save some other people some time if they are using similar hardware to me. 

One last question, sorry if it's not appropriate to chain questions on the same issue: I'm noticing my System Clock Latency Jitter is fairly high, I was wondering if this is normal. Around abs(100 us). My PCs are only running ptp4l, phc2sys, and isochron. Running ptp4l using SCHED_FIFO 99, phc2sys SCHED_FIFO 40, and isochron sender at SCHED_FIFO 99. If plus/minus 100 us latency jitter is normal for System Clock Latency then, I'll just leave it alone, no point in spending time trying to improve something that's nothing out of the ordinary. 

Thanks for all your help.

**Comment by vladimiroltean** [comment]
Make sure you don't have other services enabled which adjust the system clock, like NTP.

**Comment by stefan-ramdhan** [comment]
Yeah, that's one of the first things I checked. It might just be kernel scheduling jitter.

**Comment by vladimiroltean** [comment]
May it just be the lack of PTM, plus the inherent latency caused by PCIe transfers? Could you post a phc2sys log, to see how variable is the delay?
Here is a relevant commit for igc:
https://github.com/torvalds/linux/commit/a90ec84837325df4b9a6798c2cc0df202b5680bd

**Comment by vladimiroltean** [comment]
I've also seen systems behave much more predictably when the CPU frequency governor runs at a constant frequency, either by disabling `CONFIG_CPU_FREQ` (at kernel compile time), or by adjusting `/sys/bus/cpu/devices/${cpu}/cpufreq/scaling_min_freq` to be equal to `/sys/bus/cpu/devices/${cpu}/cpufreq/scaling_max_freq`, and `/sys/devices/system/cpu/${cpu}/cpufreq/scaling_governor` to be `performance` (at runtime).
I'd expect a kernel prepared for real time tasks to have this kind of configuration already done, but I don't know if that's the case here, so I thought I'd mention.

**Comment by stefan-ramdhan** [comment]
Sure, here is a short log of phc2sys.
[phc2sys.log](https://github.com/vladimiroltean/isochron/files/11950677/phc2sys.log)

Actually, we do have the performance governor set to `performance`, and we have the min frequency set to the max frequency already. We did this mainly because we were trying to figure out why, when we inject traffic or CPU stress, the latency measured by isochron goes down, rather than up. It was paradoxical, and we thought it was because of Intel Turbo Boost or the variable frequency, so to eliminate that, we turned Intel Turbo Boost off, and set the CPU frequency to be static, but that wasn't the cause; our latency still improves when we inject traffic oddly enough.

Are you aware of any tools/utilities that I can use to debug why Sys Clock latency jitter might be high, or why latency might be decreasing when we inject traffic?

**Comment by vladimiroltean** [comment]
To be clear, is the log that you've posted supposed to show a good or bad situation? It shows an average delay of ~1320 ns, i.e. 1.3 us. Nowhere near the "abs(100 us)" you've claimed in an earlier message. A latency of 1.3 us is about normal.

**Comment by stefan-ramdhan** [comment]
Sorry I should have been more specific with my wording. When I said "my System Clock Latency Jitter is high" I meant latency from GM System Clock Timestamp to Slave System Clock Timestamp (or `w` to `a` timestamps given by `isochron report`). When subtracting `a-w` to get latency, I can then calculate E2E latency jitter (done in a postprocessing script). It's the E2E latency jitter that is fairly high (abs(100 us)).

**Comment by vladimiroltean** [comment]
Ah, ok, you're talking about `a-w` (arrival time in `CLOCK_TAI` minus sender wakeup time in `CLOCK_TAI`). Well, that's not quite the latency between system clocks, that's the packet end-to-end latency measured across system clocks...

Anyway, you might want to check which portion is (more) jittery by comparing against a hardware timestamp on the other side (`w` against `R`, `T` against `a`) and try to find out where that comes from, using tools like `cyclictest`. The clocks are synchronized, so the comparison should be valid.

If you're into in-depth kernel debugging, `isochron-send` has a `--tracemark` option that you can use together with `CONFIG_FTRACE` and `kernelshark`, to see exactly what is holding up the packets with the longest latencies. Having trace marks inserted by isochron helps to navigate quickly to the portion of the log containing a specific packet. I haven't implemented the trace mark option for `isochron-rcv`, since optimizing the receiver wasn't very interesting to me. But, if the RX side is (more) to blame for the jitter, chances are that the problem is also simpler. "Latency that gets better with more background traffic" sounds like a classic case of IRQ coalescing. Try to turn it off through `ethtool --coalesce`.

This is very system-specific territory and I don't know what you may find.
